import { db } from "../server/db";
import { shortlistedItems } from "@shared/schema";

// Data extracted from the Shortlisted Items PDF - Complete dataset
const shortlistedItemsData = [
  // Neni Memi Brand (S.No 1-18)
  { sno: 1, category: "Namkeen", brand: "Neni Memi", item: "Aloo Bhujia", flavour: "", quantity: "16gm", mrp: "5.00" },
  { sno: 2, category: "Namkeen", brand: "Neni Memi", item: "Bhujia", flavour: "", quantity: "16gm", mrp: "5.00" },
  { sno: 3, category: "Namkeen", brand: "Neni Meml", item: "Moong Dal", flavour: "", quantity: "16gm", mrp: "5.00" },
  { sno: 4, category: "Namkeen", brand: "Neni Memi", item: "Gadbad Mixture", flavour: "", quantity: "16gm", mrp: "5.00" },
  { sno: 5, category: "Namkeen", brand: "Neni Meml", item: "Tasty Peanuts", flavour: "", quantity: "16gm", mrp: "5.00" },
  { sno: 6, category: "Namkeen", brand: "Neni Memi", item: "Corn Mixture", flavour: "", quantity: "16gm", mrp: "5.00" },
  { sno: 7, category: "Namkeen", brand: "Neni Memi", item: "Aloo Bhujia", flavour: "", quantity: "25gm", mrp: "10.00" },
  { sno: 8, category: "Namkeen", brand: "Neni Memi", item: "Bhujia", flavour: "", quantity: "25gm", mrp: "10.00" },
  { sno: 9, category: "Namkeen", brand: "Neni Memi", item: "Moong Dal", flavour: "", quantity: "25gm", mrp: "10.00" },
  { sno: 10, category: "Namkeen", brand: "Neni Memi", item: "Gadbad Mixture", flavour: "", quantity: "25gm", mrp: "10.00" },
  { sno: 11, category: "Namkeen", brand: "Neni Memi", item: "Tasty Peanuts", flavour: "", quantity: "25gm", mrp: "10.00" },
  { sno: 12, category: "Namkeen", brand: "Neni Memi", item: "Corn Mixture", flavour: "", quantity: "25gm", mrp: "10.00" },
  { sno: 13, category: "Namkeen", brand: "Neni Memi", item: "Aloo Bhujia", flavour: "", quantity: "50gm", mrp: "20.00" },
  { sno: 14, category: "Namkeen", brand: "Neni Memi", item: "Bhujia", flavour: "", quantity: "50gm", mrp: "20.00" },
  { sno: 15, category: "Namkeen", brand: "Neni Memi", item: "Moong Dal", flavour: "", quantity: "50gm", mrp: "20.00" },
  { sno: 16, category: "Namkeen", brand: "Neni Memi", item: "Gadbad Mixture", flavour: "", quantity: "50gm", mrp: "20.00" },
  { sno: 17, category: "Namkeen", brand: "Neni Memi", item: "Tasty Peanuts", flavour: "", quantity: "50gm", mrp: "20.00" },
  { sno: 18, category: "Namkeen", brand: "Neni Memi", item: "Corn Mixture", flavour: "", quantity: "50gm", mrp: "20.00" },

  // BTW Brand (Complete dataset from PDF)
  { sno: 19, category: "Namkeen", brand: "BTW", item: "Alloo Bhujia", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 20, category: "Namkeen", brand: "BTW", item: "Alloo Bhujia", flavour: "", quantity: "32gm", mrp: "10.00" },
  { sno: 21, category: "Namkeen", brand: "BTW", item: "Alloo Bhujia", flavour: "", quantity: "50gm", mrp: "20.00" },
  { sno: 22, category: "Namkeen", brand: "BTW", item: "Alloo Bhujia", flavour: "", quantity: "200gm", mrp: "55.00" },
  { sno: 23, category: "Namkeen", brand: "BTW", item: "Alloo Bhujia", flavour: "", quantity: "400gm", mrp: "110.00" },
  { sno: 24, category: "Namkeen", brand: "BTW", item: "Alloo Bhujia", flavour: "", quantity: "1000gm", mrp: "272.00" },
  { sno: 25, category: "Namkeen", brand: "BTW", item: "Badam Lachha", flavour: "", quantity: "200gm", mrp: "90.00" },
  { sno: 26, category: "Namkeen", brand: "BTW", item: "Bikaneri Bhujia", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 27, category: "Namkeen", brand: "BTW", item: "Bikaneri Bhujia", flavour: "", quantity: "32gm", mrp: "10.00" },
  { sno: 28, category: "Namkeen", brand: "BTW", item: "Bikaneri Bhujia", flavour: "", quantity: "50gm", mrp: "20.00" },
  { sno: 29, category: "Namkeen", brand: "BTW", item: "Bikaneri Bhujia", flavour: "", quantity: "200gm", mrp: "60.00" },
  { sno: 30, category: "Namkeen", brand: "BTW", item: "Bikaneri Bhujia", flavour: "", quantity: "400gm", mrp: "120.00" },
  { sno: 31, category: "Namkeen", brand: "BTW", item: "Bikaneri Bhujia", flavour: "", quantity: "1000gm", mrp: "297.00" },
  { sno: 32, category: "Namkeen", brand: "BTW", item: "Cheezy Bhujia", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 33, category: "Namkeen", brand: "BTW", item: "Cheezy Bhujia", flavour: "", quantity: "32gm", mrp: "10.00" },
  { sno: 34, category: "Namkeen", brand: "BTW", item: "Crancho", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 35, category: "Namkeen", brand: "BTW", item: "Crancho", flavour: "", quantity: "32gm", mrp: "10.00" },
  { sno: 36, category: "Namkeen", brand: "BTW", item: "Crancho", flavour: "", quantity: "50gm", mrp: "20.00" },
  { sno: 37, category: "Namkeen", brand: "BTW", item: "Diet Mixture", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 38, category: "Namkeen", brand: "BTW", item: "Diet Mixture", flavour: "", quantity: "32gm", mrp: "10.00" },
  { sno: 39, category: "Namkeen", brand: "BTW", item: "Diet Mixture", flavour: "", quantity: "50gm", mrp: "20.00" },
  { sno: 40, category: "Namkeen", brand: "BTW", item: "Diet Mixture", flavour: "", quantity: "150gm", mrp: "30.00" },
  { sno: 41, category: "Namkeen", brand: "BTW", item: "Diet Mixture", flavour: "", quantity: "200gm", mrp: "55.00" },
  { sno: 42, category: "Namkeen", brand: "BTW", item: "Hing Chana", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 43, category: "Namkeen", brand: "BTW", item: "Hing Chana", flavour: "", quantity: "32gm", mrp: "10.00" },
  { sno: 44, category: "Namkeen", brand: "BTW", item: "Kaju Mixture", flavour: "", quantity: "28gm", mrp: "10.00" },
  { sno: 45, category: "Namkeen", brand: "BTW", item: "Kaju Mixture", flavour: "", quantity: "50gm", mrp: "20.00" },
  { sno: 46, category: "Namkeen", brand: "BTW", item: "Kaju Mixture", flavour: "", quantity: "200gm", mrp: "90.00" },
  { sno: 47, category: "Namkeen", brand: "BTW", item: "Khatta Meetha", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 48, category: "Namkeen", brand: "BTW", item: "Khatta Meetha", flavour: "", quantity: "32gm", mrp: "10.00" },
  { sno: 49, category: "Namkeen", brand: "BTW", item: "Khatta Meetha", flavour: "", quantity: "50gm", mrp: "20.00" },
  { sno: 50, category: "Namkeen", brand: "BTW", item: "Khatta Meetha", flavour: "", quantity: "200gm", mrp: "55.00" },
  { sno: 51, category: "Namkeen", brand: "BTW", item: "Khatta Meetha", flavour: "", quantity: "400gm", mrp: "110.00" },
  { sno: 52, category: "Namkeen", brand: "BTW", item: "Moong Dal", flavour: "", quantity: "1000gm", mrp: "272.00" },
  { sno: 53, category: "Namkeen", brand: "BTW", item: "Moong Dal", flavour: "", quantity: "14gm", mrp: "5.00" },
  { sno: 54, category: "Namkeen", brand: "BTW", item: "Moong Dal", flavour: "", quantity: "28gm", mrp: "10.00" },
  { sno: 55, category: "Namkeen", brand: "BTW", item: "Moong Dal", flavour: "", quantity: "50gm", mrp: "20.00" },
  { sno: 56, category: "Namkeen", brand: "BTW", item: "Moong Dal", flavour: "", quantity: "200gm", mrp: "60.00" },
  { sno: 57, category: "Namkeen", brand: "BTW", item: "Navratan Mixture", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 58, category: "Namkeen", brand: "BTW", item: "Navratan Mixture", flavour: "", quantity: "32gm", mrp: "10.00" },
  { sno: 59, category: "Namkeen", brand: "BTW", item: "Navratan Mixture", flavour: "", quantity: "50gm", mrp: "20.00" },
  { sno: 60, category: "Namkeen", brand: "BTW", item: "Navratan Mixture", flavour: "", quantity: "200gm", mrp: "55.00" },
  { sno: 61, category: "Namkeen", brand: "BTW", item: "Navratan Mixture", flavour: "", quantity: "400gm", mrp: "110.00" },
  { sno: 62, category: "Namkeen", brand: "BTW", item: "Navratan Mixture", flavour: "", quantity: "1000gm", mrp: "272.00" },
  { sno: 63, category: "Namkeen", brand: "BTW", item: "Plain Boondi", flavour: "", quantity: "42gm", mrp: "10.00" },
  { sno: 64, category: "Namkeen", brand: "BTW", item: "Plain Boondi", flavour: "", quantity: "50gm", mrp: "20.00" },
  { sno: 65, category: "Namkeen", brand: "BTW", item: "Plain Boondi", flavour: "", quantity: "200gm", mrp: "55.00" },
  { sno: 66, category: "Namkeen", brand: "BTW", item: "Punjabi Crisp", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 67, category: "Namkeen", brand: "BTW", item: "Punjabi Crisp", flavour: "", quantity: "32gm", mrp: "10.00" },
  { sno: 68, category: "Namkeen", brand: "BTW", item: "Salted Peanuts", flavour: "", quantity: "14gm", mrp: "5.00" },
  { sno: 69, category: "Namkeen", brand: "BTW", item: "Salted Peanuts", flavour: "", quantity: "28gm", mrp: "10.00" },
  { sno: 70, category: "Namkeen", brand: "BTW", item: "Spicy Nut", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 71, category: "Namkeen", brand: "BTW", item: "Spicy Nut", flavour: "", quantity: "32gm", mrp: "10.00" },
  { sno: 72, category: "Namkeen", brand: "BTW", item: "Spicy Nut", flavour: "", quantity: "50gm", mrp: "20.00" },
  { sno: 73, category: "Namkeen", brand: "BTW", item: "Spicy Nut", flavour: "", quantity: "200gm", mrp: "55.00" },

  // Daaji Brand (Complete dataset)
  { sno: 74, category: "Namkeen", brand: "Daaji", item: "Jeera Papad", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 75, category: "Namkeen", brand: "Daaji", item: "Bikaneri Bhujia", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 76, category: "Namkeen", brand: "Daaji", item: "Navratan Mixture", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 77, category: "Namkeen", brand: "Daaji", item: "Aloo Bhujia", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 78, category: "Namkeen", brand: "Daaji", item: "Khatta Mitha", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 79, category: "Namkeen", brand: "Daaji", item: "Akhiri Pasta", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 80, category: "Namkeen", brand: "Daaji", item: "Cocktail Nuts", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 81, category: "Namkeen", brand: "Daaji", item: "Malai Sev", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 82, category: "Namkeen", brand: "Daaji", item: "Punjabi Tadka", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 83, category: "Namkeen", brand: "Daaji", item: "Masala Blast", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 84, category: "Namkeen", brand: "Daaji", item: "Salted Peanut", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 85, category: "Namkeen", brand: "Daaji", item: "Moongdal", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 86, category: "Namkeen", brand: "Daaji", item: "Akhiri Pasta", flavour: "", quantity: "15gm", mrp: "5.00" },
  { sno: 87, category: "Namkeen", brand: "Daaji", item: "Jeera Papad", flavour: "", quantity: "30gm", mrp: "10.00" },
  { sno: 88, category: "Namkeen", brand: "Daaji", item: "Bikaneri Bhujia", flavour: "", quantity: "30gm", mrp: "10.00" },
  { sno: 89, category: "Namkeen", brand: "Daaji", item: "Navratan Mixture", flavour: "", quantity: "30gm", mrp: "10.00" },
  { sno: 90, category: "Namkeen", brand: "Daaji", item: "Aloo Bhujia", flavour: "", quantity: "30gm", mrp: "10.00" },
  { sno: 91, category: "Namkeen", brand: "Daaji", item: "Khatta Mitha", flavour: "", quantity: "30gm", mrp: "10.00" },
  { sno: 92, category: "Namkeen", brand: "Daaji", item: "Akhiri Pasta", flavour: "", quantity: "30gm", mrp: "10.00" },
  { sno: 93, category: "Namkeen", brand: "Daaji", item: "Cocktail Nuts", flavour: "", quantity: "30gm", mrp: "10.00" },
  { sno: 94, category: "Namkeen", brand: "Daaji", item: "Malai Sev", flavour: "", quantity: "30gm", mrp: "10.00" },
  { sno: 95, category: "Namkeen", brand: "Daaji", item: "Punjabi Tadka", flavour: "", quantity: "30gm", mrp: "10.00" },
  { sno: 96, category: "Namkeen", brand: "Daaji", item: "Masala Blast", flavour: "", quantity: "30gm", mrp: "10.00" },
  { sno: 97, category: "Namkeen", brand: "Daaji", item: "Salted Peanut", flavour: "", quantity: "30gm", mrp: "10.00" },
  { sno: 98, category: "Namkeen", brand: "Daaji", item: "Moongdal", flavour: "", quantity: "30gm", mrp: "10.00" },
  { sno: 99, category: "Namkeen", brand: "Daaji", item: "Akhiri Pasta", flavour: "", quantity: "30gm", mrp: "10.00" },
  { sno: 100, category: "Namkeen", brand: "Daaji", item: "Jeera Papad", flavour: "", quantity: "55gm", mrp: "20.00" },
  { sno: 101, category: "Namkeen", brand: "Daaji", item: "Bikaneri Bhujia", flavour: "", quantity: "55gm", mrp: "20.00" },
  { sno: 102, category: "Namkeen", brand: "Daaji", item: "Navratan Mixture", flavour: "", quantity: "55gm", mrp: "20.00" },
  { sno: 103, category: "Namkeen", brand: "Daaji", item: "Aloo Bhujia", flavour: "", quantity: "55gm", mrp: "20.00" },
  { sno: 104, category: "Namkeen", brand: "Daaji", item: "Khatta Mitha", flavour: "", quantity: "55gm", mrp: "20.00" },
  { sno: 105, category: "Namkeen", brand: "Daaji", item: "Akhiri Pasta", flavour: "", quantity: "55gm", mrp: "20.00" },
  { sno: 106, category: "Namkeen", brand: "Daaji", item: "Cocktail Nuts", flavour: "", quantity: "55gm", mrp: "20.00" },
  { sno: 107, category: "Namkeen", brand: "Daaji", item: "Malai Sev", flavour: "", quantity: "55gm", mrp: "20.00" },
  { sno: 108, category: "Namkeen", brand: "Daaji", item: "Punjabi Tadka", flavour: "", quantity: "55gm", mrp: "20.00" },
  { sno: 109, category: "Namkeen", brand: "Daaji", item: "Masala Blast", flavour: "", quantity: "55gm", mrp: "20.00" },
  { sno: 110, category: "Namkeen", brand: "Daaji", item: "Salted Peanut", flavour: "", quantity: "55gm", mrp: "20.00" },
  { sno: 111, category: "Namkeen", brand: "Daaji", item: "Moongdal", flavour: "", quantity: "55gm", mrp: "20.00" },
  { sno: 112, category: "Namkeen", brand: "Daaji", item: "Akhiri Pasta", flavour: "", quantity: "55gm", mrp: "20.00" },

  // Tip Top Brand (Complete dataset from PDF)
  { sno: 113, category: "Namkeen", brand: "Tip Top", item: "Aloo Bhujia", flavour: "", quantity: "16gm", mrp: "5.00" },
  { sno: 114, category: "Namkeen", brand: "Tip Top", item: "Aloo Bhujia", flavour: "", quantity: "36gm", mrp: "10.00" },
  { sno: 115, category: "Namkeen", brand: "Tip Top", item: "Aloo Bhujia", flavour: "", quantity: "37gm", mrp: "15.00" },
  { sno: 116, category: "Namkeen", brand: "Tip Top", item: "Aloo Bhujia", flavour: "", quantity: "72gm", mrp: "20.00" },
  { sno: 117, category: "Namkeen", brand: "Tip Top", item: "Aloo Bhujia", flavour: "", quantity: "250gm", mrp: "75.00" },
  { sno: 118, category: "Namkeen", brand: "Tip Top", item: "Bikaner Bhujia", flavour: "", quantity: "16gm", mrp: "5.00" },
  { sno: 119, category: "Namkeen", brand: "Tip Top", item: "Bikaner Bhujia", flavour: "", quantity: "36gm", mrp: "10.00" },
  { sno: 120, category: "Namkeen", brand: "Tip Top", item: "Bikaner Bhujia", flavour: "", quantity: "37gm", mrp: "15.00" },
  { sno: 121, category: "Namkeen", brand: "Tip Top", item: "Bikaner Bhujia", flavour: "", quantity: "72gm", mrp: "20.00" },
  { sno: 122, category: "Namkeen", brand: "Tip Top", item: "Bikaner Bhujia", flavour: "", quantity: "250gm", mrp: "75.00" },
  { sno: 123, category: "Namkeen", brand: "Tip Top", item: "Boondi", flavour: "", quantity: "36gm", mrp: "10.00" },
  { sno: 124, category: "Namkeen", brand: "Tip Top", item: "Boondi", flavour: "", quantity: "37gm", mrp: "15.00" },
  { sno: 125, category: "Namkeen", brand: "Tip Top", item: "Boondi", flavour: "", quantity: "72gm", mrp: "20.00" },
  { sno: 126, category: "Namkeen", brand: "Tip Top", item: "Boondi", flavour: "", quantity: "250gm", mrp: "75.00" },
  { sno: 127, category: "Namkeen", brand: "Tip Top", item: "Chatori Katori", flavour: "", quantity: "18gm", mrp: "5.00" },
  { sno: 128, category: "Namkeen", brand: "Tip Top", item: "Chatori Katori", flavour: "", quantity: "36gm", mrp: "10.00" },
  { sno: 129, category: "Namkeen", brand: "Tip Top", item: "Chatori Katori", flavour: "", quantity: "37gm", mrp: "15.00" },
  { sno: 130, category: "Namkeen", brand: "Tip Top", item: "Corn Puff", flavour: "American Cheese", quantity: "120gm", mrp: "50.00" },
  { sno: 131, category: "Namkeen", brand: "Tip Top", item: "Corn Puff", flavour: "Khatta Milha", quantity: "120gm", mrp: "50.00" },
  { sno: 132, category: "Namkeen", brand: "Tip Top", item: "Corn Puff", flavour: "Masala", quantity: "120gm", mrp: "50.00" },
  { sno: 133, category: "Namkeen", brand: "Tip Top", item: "Corn Puff", flavour: "Peri Peri", quantity: "120gm", mrp: "50.00" },
  { sno: 134, category: "Namkeen", brand: "Tip Top", item: "Corn Puff", flavour: "Salted", quantity: "120gm", mrp: "50.00" },
  { sno: 135, category: "Namkeen", brand: "Tip Top", item: "Corn Puff", flavour: "Pudina", quantity: "120gm", mrp: "50.00" },
  { sno: 136, category: "Namkeen", brand: "Tip Top", item: "Disco Papad", flavour: "", quantity: "20gm", mrp: "10.00" },
  { sno: 137, category: "Namkeen", brand: "Tip Top", item: "Disco Papad", flavour: "", quantity: "21gm", mrp: "15.00" },
  { sno: 138, category: "Namkeen", brand: "Tip Top", item: "Disco Papad", flavour: "", quantity: "40gm", mrp: "20.00" },
  { sno: 139, category: "Namkeen", brand: "Tip Top", item: "Disco Papad", flavour: "", quantity: "200gm", mrp: "75.00" },
  { sno: 140, category: "Namkeen", brand: "Tip Top", item: "Hing Jeera Chana", flavour: "", quantity: "180gm", mrp: "45.00" },
  { sno: 141, category: "Namkeen", brand: "Tip Top", item: "Hing Jeera Chana", flavour: "", quantity: "36gm", mrp: "10.00" },
  { sno: 142, category: "Namkeen", brand: "Tip Top", item: "Hing Jeera Chana", flavour: "", quantity: "37gm", mrp: "15.00" },
  { sno: 143, category: "Namkeen", brand: "Tip Top", item: "Hing Jeera Chana", flavour: "", quantity: "72gm", mrp: "20.00" },
  { sno: 144, category: "Namkeen", brand: "Tip Top", item: "Hing Jeera Peanut", flavour: "", quantity: "180gm", mrp: "45.00" },
  { sno: 145, category: "Namkeen", brand: "Tip Top", item: "Khatta Mitha", flavour: "", quantity: "250gm", mrp: "75.00" },
  { sno: 146, category: "Namkeen", brand: "Tip Top", item: "Khil Chana", flavour: "", quantity: "180gm", mrp: "40.00" },
  { sno: 147, category: "Namkeen", brand: "Tip Top", item: "Krari Papdi Achhar", flavour: "", quantity: "25gm", mrp: "16.00" },
  { sno: 148, category: "Namkeen", brand: "Tip Top", item: "Krari Papdi Achhar", flavour: "", quantity: "26gm", mrp: "15.00" },
  { sno: 149, category: "Namkeen", brand: "Tip Top", item: "Krari Papdi Achhar", flavour: "", quantity: "50gm", mrp: "20.00" },
  { sno: 150, category: "Namkeen", brand: "Tip Top", item: "Krari Papdi Achhar", flavour: "", quantity: "200gm", mrp: "75.00" },
  { sno: 151, category: "Namkeen", brand: "Tip Top", item: "Krari Peanut", flavour: "", quantity: "16gm", mrp: "5.00" },
  { sno: 152, category: "Namkeen", brand: "Tip Top", item: "Krari Peanut", flavour: "", quantity: "36gm", mrp: "10.00" },
  { sno: 153, category: "Namkeen", brand: "Tip Top", item: "Krari Peanut", flavour: "", quantity: "37gm", mrp: "15.00" },
  { sno: 154, category: "Namkeen", brand: "Tip Top", item: "Krari Peanut", flavour: "", quantity: "72gm", mrp: "20.00" },
  { sno: 155, category: "Namkeen", brand: "Tip Top", item: "Krari Peanut", flavour: "", quantity: "250gm", mrp: "75.00" },
  { sno: 156, category: "Namkeen", brand: "Tip Top", item: "Kurrey", flavour: "Tomato/Masala", quantity: "18gm", mrp: "5.00" },
  { sno: 157, category: "Namkeen", brand: "Tip Top", item: "Kurrey", flavour: "Tomato/Masala", quantity: "36gm", mrp: "10.00" },
  { sno: 158, category: "Namkeen", brand: "Tip Top", item: "Kurrey", flavour: "Tomato/Masala", quantity: "37gm", mrp: "15.00" },
  { sno: 159, category: "Namkeen", brand: "Tip Top", item: "Lahsun Sev", flavour: "", quantity: "16gm", mrp: "5.00" },
  { sno: 160, category: "Namkeen", brand: "Tip Top", item: "Lahsun Sev", flavour: "", quantity: "36gm", mrp: "10.00" },
  { sno: 161, category: "Namkeen", brand: "Tip Top", item: "Lahsun Sev", flavour: "", quantity: "37gm", mrp: "15.00" },
  { sno: 162, category: "Namkeen", brand: "Tip Top", item: "Lahsun Sev", flavour: "", quantity: "72gm", mrp: "20.00" },
  { sno: 163, category: "Namkeen", brand: "Tip Top", item: "Lahsun Sev", flavour: "", quantity: "250gm", mrp: "75.00" },
];

async function seedShortlistedItems() {
  try {
    console.log("Starting to seed shortlisted items...");
    
    // Clear existing data
    await db.delete(shortlistedItems);
    console.log("Cleared existing shortlisted items");
    
    // Insert new data
    for (const item of shortlistedItemsData) {
      await db.insert(shortlistedItems).values({
        sno: item.sno,
        category: item.category,
        brand: item.brand,
        item: item.item,
        flavour: item.flavour || null,
        quantity: item.quantity,
        mrp: item.mrp,
      });
    }
    
    console.log(`Successfully seeded ${shortlistedItemsData.length} shortlisted items`);
  } catch (error) {
    console.error("Error seeding shortlisted items:", error);
  }
}

seedShortlistedItems();